spring:
  profiles:
    active: prod
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@127.0.0.1:1521:orcl
    username: sboot
    password: sboot
    # HikariCP settings
    # spring.datasource.hikari.*
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
  thymeleaf:
    cache: true
    check-template: true
    content-type: text/html
    encoding: utf-8
    excluded-view-names:
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
    template-resolver-order:
